config/routes.rb
TinyPosts::Application.routes.draw do

  root 'static#landing'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update]
  resources :posts

  get 'profile/:id', to: 'users#show', as: 'user_profile'

  

end

app/models/posts.rb
class Posts < ActiveRecord::Base
  belongs_to :user
	# each post must have content and a user_id
	validates_presence_of :content, :user_id
	# content may not be longer than 140 characters in length
	validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
  # if a user is deleted, delete all their posts
	has_many :posts, dependent: :destroy

	validates_presence_of :password, :on => :create
	validates_presence_of :password_confirmation, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	# look in to cookie jar for user_id cookie
  	if cookies[:user_id]
  		# dip in to the signed cookie jar for our user_id value
  		user_id = cookies.signed[:user_id]
  		# find and return the user for that id 
  		User.find_by_id(user_id)
  	end
  end

  def sign_in user
  	# encrypt the value of our cookie
    cookies.signed[:user_id] =  user.id
  end

  def signed_in?
  	current_user # nil or #<User>
  end

  def authenticate
  	if !signed_in?
  		redirect_to new_session_path
  	end
  end

  # make current_user and signed_in? methods available inside of views
  helper_method :current_user, :signed_in?
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate

	# GET /post
	def index
		@posts = Posts.order("id desc")
	end

	# GET /post/new
	def new
		@post = Posts.new
	end

	# POST /post
	def create
		@post = Posts.new(posts_parameters)
		@post.user_id = current_user.id

		if @post.save
			redirect_to posts_path
		else
			render :new
		end
	end

	private
		# only allow content and author data to be submitted.
		def posts_parameters
			params.require(:posts).permit(:content)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:sessions][:email])
		if user && user.authenticate(params[:sessions][:password])
			sign_in(user)
			redirect_to posts_path
		else
			# invalid log in credentials
			flash.now[:error] = "Unable to log in with the supplied credentials."
			render :new
		end
	end

	def destroy
		cookies.delete(:user_id)
		redirect_to root_path
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def landing
  	if signed_in?
  		redirect_to posts_path
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_create_parameters)

		if @user.save
			sign_in(@user)
			redirect_to posts_path
		else
			render :new
		end
	end

	def show
		@user = User.find_by_id(params[:id])

		if @user.nil?
			redirect_to root_path
		end
	end

	def edit
		@user = User.find_by_id(params[:id])

		if current_user != @user
			redirect_to root_path
		end
	end

	def update
		@user = current_user
		@user.update(user_update_parameters)

		if @user.save
			redirect_to user_profile_path
		else
			render :edit
		end
	end

	private
		# only allow content and author data to be submitted.
		def user_create_parameters
			params.require(:user).permit(:email, :username, :password, :password_confirmation)
		end

		def user_update_parameters
			params.require(:user).permit(:username)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_url(size=20)
		# asumes user is logged in.
		hashed_email = Digest::MD5.hexdigest(current_user.email)
		"http://www.gravatar.com/avatar/#{hashed_email}?s=#{size}"
	end

	def gravatar_url_for(email, size=20)
		hashed_email = Digest::MD5.hexdigest(email)
		"http://www.gravatar.com/avatar/#{hashed_email}?s=#{size}"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Tiny Poster | <%= content_for?(:title) ? yield(:title) : "Index" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="<%= root_path %>">Tiny Poster</a></h1>
          </li>
        </ul>

        <section class="top-bar-section">
          <ul class="right">
            <% if signed_in? %>
              <li class="has-dropdown">
                <%= link_to current_user.email, '#' %>
                <ul class="dropdown">
                  <li class="active"><%= link_to "New Post", new_post_path %></li>
                  <li><%= link_to "View Profile", user_profile_path(current_user) %></li>
                  <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                  <li><%= link_to "Sign Out", session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
          </ul>
        </section>
      </nav>
    </div>
    <br />
    <div class="row">
      <div class="small-12">
        <%= yield %>
      </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/posts/index.html.erb
<% content_for(:title, "Listing Posts") %>
<h1>Latest Posts</h1>
<% @posts.each do |post| %>
	<div class="post-wrapper">
		<div class="post-content">
			<%= post.content  %>
		</div>
		<div class="post-author">
			<% author = User.find(post.user_id) %>
			&mdash; <%= link_to author.username, user_profile_path(author) %>
		</div>
	</div>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: { action: 'create' } do |f| %>
	<fieldset>
		<legend>Create a Tiny Post</legend>
		<% # for any error create a small warning label %>
		<% if @post.errors.any? %>
			<% @post.errors.full_messages.reverse.each do |error_message| %>
			<div class="alert-box warning radius">
				<%= error_message %>
			</div>
			<% end %>
		<% end %>
		<div class="row">
			<div class="small-12 columns">
				<% placement = ["Hola, amigo!", "こんにちは！", "Hello, world!", "Write in me!"].sample %>
				<%= f.text_area :content, placeholder: placement, maxlength: 140, required: "required" %>
			</div>
		</div>
		<div class="row">
			<div class="small-12 columns">
				<% button_labels = ["Share!", "Create!", "Launch!"].sample %>
				<%= f.submit button_labels, class: "button expand radius" %>
			</div>
		</div>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |form| %>
	<fieldset>
		<legend>Update Account</legend>
		<% if @user.errors.any? %>
		<h1> ERRRROSS </h1>
			<% @user.errors.full_messages.each do |msg| %>
			<%= msg %><br />
			<% end %>
		<% end %>
		<div>
			<%= form.label :username %>
			<%= form.text_field :username %> 
			<%= form.label :password %>
			<%= form.password_field :password %>
			<%= form.label :password_confirmation %>
			<%= form.password_field :password_confirmation %>
		</div>
		<%= form.submit "Sign Up" %>
</fieldset>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
	<fieldset>
		<legend>Creating Account</legend>
		<% if @user.errors.any? %>
		<h1> ERRRROSS </h1>
			<% @user.errors.full_messages.each do |msg| %>
			<%= msg %><br />
			<% end %>
		<% end %>
		<div>
			<%= form.label :email %>
			<%= form.email_field :email %> 
			<%= form.label :username %>
			<%= form.text_field :username %> 
			<%= form.label :password %>
			<%= form.password_field :password %>
			<%= form.label :password_confirmation %>
			<%= form.password_field :password_confirmation %>
		</div>
		<%= form.submit "Sign Up" %>
</fieldset>
<% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="small-3 columns">
		<%= image_tag gravatar_url_for(@user.email, 200) %>
		<ul class="side-nav">
		  <li><a href="#">Link 1</a></li>
		  <li><a href="#">Link 2</a></li>
		  <li><a href="#">Link 3</a></li>
		  <li><a href="#">Link 4</a></li>
		</ul>
	</div>
	<div class="small-9 columns">
		<h1><%= @user.username %></h1>
	</div>
</div>